require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LogoEntriesController do

  # This should return the minimal set of attributes required to create a valid
  # LogoEntry. As you add validations to LogoEntry, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LogoEntriesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all logo_entries as @logo_entries" do
      logo_entry = LogoEntry.create! valid_attributes
      get :index, {}, valid_session
      assigns(:logo_entries).should eq([logo_entry])
    end
  end

  describe "GET show" do
    it "assigns the requested logo_entry as @logo_entry" do
      logo_entry = LogoEntry.create! valid_attributes
      get :show, {:id => logo_entry.to_param}, valid_session
      assigns(:logo_entry).should eq(logo_entry)
    end
  end

  describe "GET new" do
    it "assigns a new logo_entry as @logo_entry" do
      get :new, {}, valid_session
      assigns(:logo_entry).should be_a_new(LogoEntry)
    end
  end

  describe "GET edit" do
    it "assigns the requested logo_entry as @logo_entry" do
      logo_entry = LogoEntry.create! valid_attributes
      get :edit, {:id => logo_entry.to_param}, valid_session
      assigns(:logo_entry).should eq(logo_entry)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new LogoEntry" do
        expect {
          post :create, {:logo_entry => valid_attributes}, valid_session
        }.to change(LogoEntry, :count).by(1)
      end

      it "assigns a newly created logo_entry as @logo_entry" do
        post :create, {:logo_entry => valid_attributes}, valid_session
        assigns(:logo_entry).should be_a(LogoEntry)
        assigns(:logo_entry).should be_persisted
      end

      it "redirects to the created logo_entry" do
        post :create, {:logo_entry => valid_attributes}, valid_session
        response.should redirect_to(LogoEntry.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved logo_entry as @logo_entry" do
        # Trigger the behavior that occurs when invalid params are submitted
        LogoEntry.any_instance.stub(:save).and_return(false)
        post :create, {:logo_entry => {  }}, valid_session
        assigns(:logo_entry).should be_a_new(LogoEntry)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        LogoEntry.any_instance.stub(:save).and_return(false)
        post :create, {:logo_entry => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested logo_entry" do
        logo_entry = LogoEntry.create! valid_attributes
        # Assuming there are no other logo_entries in the database, this
        # specifies that the LogoEntry created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        LogoEntry.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => logo_entry.to_param, :logo_entry => { "these" => "params" }}, valid_session
      end

      it "assigns the requested logo_entry as @logo_entry" do
        logo_entry = LogoEntry.create! valid_attributes
        put :update, {:id => logo_entry.to_param, :logo_entry => valid_attributes}, valid_session
        assigns(:logo_entry).should eq(logo_entry)
      end

      it "redirects to the logo_entry" do
        logo_entry = LogoEntry.create! valid_attributes
        put :update, {:id => logo_entry.to_param, :logo_entry => valid_attributes}, valid_session
        response.should redirect_to(logo_entry)
      end
    end

    describe "with invalid params" do
      it "assigns the logo_entry as @logo_entry" do
        logo_entry = LogoEntry.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LogoEntry.any_instance.stub(:save).and_return(false)
        put :update, {:id => logo_entry.to_param, :logo_entry => {  }}, valid_session
        assigns(:logo_entry).should eq(logo_entry)
      end

      it "re-renders the 'edit' template" do
        logo_entry = LogoEntry.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LogoEntry.any_instance.stub(:save).and_return(false)
        put :update, {:id => logo_entry.to_param, :logo_entry => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested logo_entry" do
      logo_entry = LogoEntry.create! valid_attributes
      expect {
        delete :destroy, {:id => logo_entry.to_param}, valid_session
      }.to change(LogoEntry, :count).by(-1)
    end

    it "redirects to the logo_entries list" do
      logo_entry = LogoEntry.create! valid_attributes
      delete :destroy, {:id => logo_entry.to_param}, valid_session
      response.should redirect_to(logo_entries_url)
    end
  end

end
